name: simpler_weather_app_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  anim_search_bar: ^2.0.3
  flutter:
    sdk: flutter
  geocoding: ^2.1.0
  geolocator: ^10.0.0
  http: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
